export const items = [
  {
    id: 1,
    title: 'Passionflower',
    img: '/public/images/ananas.png',
    state: false,
  },
  {
    id: 2,
    title: 'Banana',
    img: '/public/images/apple.png',
    state: false,
  },
  {
    id: 3,
    title: 'Breakfast',
    img: '/public/images/breakfast.jpeg',
    state: true,
  },
  {
    id: 4,
    title: 'MilkBurger',
    img: '/public/images/cheeseBurger.jpeg',
    state: false,
  },
  {
    id: 5,
    title: 'CheeseBurger & Fries',
    img: '/public/images/CheeseBurgerChips.jpeg',
    state: true,
  },
  {
    id: 6,
    title: 'Strawberry',
    img: '/public/images/cherry.png',
    state: false,
  },
  {
    id: 7,
    title: 'Chocolate Milkshake',
    img: '/public/images/chocolateMilkshake.jpeg',
    state: true,
  },
  {
    id: 8,
    title: 'Donuts Milkshake',
    img: '/public/images/donutsMilkshake.jpeg',
    state: true,
  },
  {
    id: 9,
    title: 'Vegetables Salad',
    img: '/public/images/fruitsSalad.png',
    state: false,
  },
  {
    id: 10,
    title: 'Hamburger & Fries',
    img: '/public/images/hamburgerAndChips.jpeg',
    state: true,
  },
  {
    id: 11,
    title: 'Kiwi',
    img: '/public/images/kiwi.png',
    state: true,
  },
  {
    id: 12,
    title: 'Lemon',
    img: '/public/images/orange.png',
    state: false,
  },
  {
    id: 13,
    title: 'Pancakes',
    img: '/public/images/pancakes.jpeg',
    state: true,
  },
  {
    id: 14,
    title: 'Papaya',
    img: '/public/images/papaya.png',
    state: true,
  },
  {
    id: 15,
    title: 'Pitaya',
    img: '/public/images/pitaya.png',
    state: true,
  },
  {
    id: 16,
    title: 'Sandwich',
    img: '/public/images/sandwich.jpeg',
    state: true,
  },
  {
    id: 17,
    title: 'Steak Meal',
    img: '/public/images/steakMeal.jpeg',
    state: true,
  },
  {
    id: 18,
    title: 'Cherry',
    img: '/public/images/strawberry.png',
    state: false,
  },
  {
    id: 19,
    title: 'Vanilla Milkshake',
    img: '/public/images/vanillaMilkshake.jpeg',
    state: true,
  },
  {
    id: 20,
    title: 'Melon',
    img: '/public/images/watermelon.png',
    state: false,
  },
]
